name: Multiline Argument

on: push

jobs:
    second_job:
        name: first_job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Action
              uses: actions/checkout@v4
            - name: Multiline Arguments
              run: |
                echo "My First Github Action Job" 
                ls -ltra
                cat README.md
